import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{MapPin,Navigation,Compass,QrCode,Trophy,User,Palette,BookOpen,Map as MapIcon,Footprints,CheckCircle2,Lock,Camera,Route,Search,RefreshCcw,ScanLine,ChevronRight,Star,Info,LocateFixed,Home as HomeIcon,Building2,Images,Ticket,MapPinned}from'lucide-react';
import turtleData from './turtleTrail.json';
import artistData from './artists.json';
import pathData from './storyPaths.json';
import achievementData from './achievements.json';
import './styles.css';

const key='rr-integrated-phase3b-v1';
const seed={points:650,visited:['outlaw','bartholomew'],scanned:['outlaw'],photos:['outlaw'],viewedShell:['outlaw','bartholomew'],viewedArtists:['Nelson P. Nelson'],completedPaths:[],stamps:['Caldwell']};
const load=()=>{try{return JSON.parse(localStorage.getItem(key))||seed}catch{return seed}};
const save=v=>localStorage.setItem(key,JSON.stringify(v));
const turtles=turtleData.turtles;
const artists=artistData.artists;
const storyPaths=pathData.storyPaths;
const achievements=achievementData.achievements;
const collections=[
 {id:'turtle',title:'Caldwell Turtle Trail',status:'Complete feature demo',text:'Behind the Shell, Meet the Artists, story paths, Near Me, passport, QR demo, and map for all 12 turtles.',count:'12 sculptures',image:'/images/turtles/outlaw.jpg'},
 {id:'murals',title:'Caldwell Mural Quest',status:'Next content build',text:'Walking mural route framework ready for mural images, map pins, QR codes, and story captions.',count:'Walking tour',image:'/images/sketches/bartholomew.png'},
 {id:'badges',title:'Fallen Badges of Caldwell',status:'Collection shell',text:'Lawmen remembrance card collection with passport and card unlock framework.',count:'8 cards',image:'/images/sketches/earp.jpeg'},
 {id:'women',title:'Women of the Border Queen',status:'Collection shell',text:'Frontier women card collection and storytelling trail framework.',count:'12 cards',image:'/images/sketches/blanche.png'},
 {id:'legends',title:'Borderlands Legends',status:'Needs production cards added',text:'Caldwell and Borderlands notable people collection, ready for the real card artwork package.',count:'8 cards',image:'/images/sketches/cosmo.jpeg'}
];
const towns=['Caldwell','Wellington','South Haven','Argonia','Conway Springs','Belle Plaine','Oxford','Mulvane','Winfield','Arkansas City','Braman'];
function haversine(a,b){const R=3958.8;const dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180;const lat1=a.lat*Math.PI/180,lat2=b.lat*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function App(){
 const[view,setView]=useState('home'),[selected,setSelected]=useState(turtles[0]),[progress,setProgress]=useState(load),[pos,setPos]=useState(null),[query,setQuery]=useState('');
 useEffect(()=>save(progress),[progress]);
 useEffect(()=>{navigator.serviceWorker?.register('/sw.js').catch(()=>{})},[]);
 function update(type,turtle){setProgress(p=>{const field=type==='visit'?'visited':type==='scan'?'scanned':type==='photo'?'photos':'viewedShell';if(p[field].includes(turtle.slug))return p;const add=type==='visit'?turtle.discoveryPoints:type==='scan'?turtle.scanPoints:type==='photo'?25:10;return{...p,points:p.points+add,[field]:[...p[field],turtle.slug]}})}
 function markArtist(name){setProgress(p=>p.viewedArtists.includes(name)?p:{...p,points:p.points+15,viewedArtists:[...p.viewedArtists,name]})}
 function completePath(path){setProgress(p=>p.completedPaths.includes(path.name)?p:{...p,points:p.points+100,completedPaths:[...p.completedPaths,path.name]})}
 const api={view,setView,selected,setSelected,progress,setProgress,update,markArtist,completePath,pos,setPos,query,setQuery};
 return <><main className="app">{view==='home'&&<SiteHome {...api}/>} {view==='towns'&&<Towns {...api}/>} {view==='collections'&&<Collections {...api}/>} {view==='caldwell'&&<CaldwellHub {...api}/>} {view==='turtleHome'&&<TurtleHome {...api}/>} {view==='trail'&&<Trail {...api}/>} {view==='turtle'&&<TurtleDetail {...api}/>} {view==='map'&&<TurtleMap {...api}/>} {view==='near'&&<NearMe {...api}/>} {view==='artists'&&<Artists {...api}/>} {view==='paths'&&<StoryPaths {...api}/>} {view==='passport'&&<Passport {...api}/>} {view==='scan'&&<Scan {...api}/>} {view==='profile'&&<Profile {...api}/>}</main><Nav view={view} setView={setView}/></>}
function completion(progress){return{visited:progress.visited.length,scanned:progress.scanned.length,photos:progress.photos.length,shell:progress.viewedShell.length,total:turtles.length}}
function SiteHome(p){const c=completion(p.progress);return <><section className="hero"><div className="hero-copy"><div className="eyebrow">RURAL ROUTES EXPLORER</div><h1>Adventure first. Collection second.</h1><p className="lead">A tourism PWA for towns, routes, side quests, public art, history cards, QR unlocks, passport stamps, and local discovery.</p><div className="actions"><button onClick={()=>p.setView('caldwell')}><Building2/>Explore Caldwell</button><button className="secondary" onClick={()=>p.setView('collections')}><Images/>Collections</button><button className="ghost" onClick={()=>p.setView('turtleHome')}><Footprints/>Turtle Trail</button></div></div><div className="hero-card"><img src="/images/turtles/outlaw.jpg"/><div><b>{c.visited}/12</b><span>Turtle Trail discoveries</span></div></div></section><Stats progress={p.progress}/><section className="section-head"><div><span className="eyebrow">FEATURED SIDE QUEST</span><h2>Caldwell Turtle Trail Complete Edition</h2></div><button className="ghost" onClick={()=>p.setView('turtleHome')}>Open <ChevronRight/></button></section><div className="feature-grid"><Feature icon={<BookOpen/>} title="Behind the Shell" text="Design stories and symbolism for each sculpture." go={()=>p.setView('trail')}/><Feature icon={<Palette/>} title="Meet the Artists" text="Artist bios and turtle assignments." go={()=>p.setView('artists')}/><Feature icon={<Route/>} title="Story Paths" text="Themed routes through the same collection." go={()=>p.setView('paths')}/><Feature icon={<MapPinned/>} title="Near Me + Map" text="Distance sorting and all 12 map pins." go={()=>p.setView('near')}/></div><section className="section-head"><div><span className="eyebrow">SITE PREVIEW</span><h2>Collections across the Borderlands</h2></div><button className="ghost" onClick={()=>p.setView('collections')}>View all</button></section><CollectionGrid setView={p.setView}/></>}
function CaldwellHub(p){return <><section className="hero"><div><span className="eyebrow">TOWN HUB</span><h1>Caldwell, Kansas</h1><p className="lead">The first complete Rural Routes demo town: turtle sculptures, murals, lawmen history, Border Queen stories, legends, and walkable side quests.</p><div className="actions"><button onClick={()=>p.setView('turtleHome')}><Footprints/>Turtle Trail</button><button className="secondary" onClick={()=>p.setView('collections')}><Images/>All collections</button><button className="ghost" onClick={()=>p.setView('map')}><MapIcon/>Open map</button></div></div><div className="hero-card"><img src="/images/turtles/bartholomew.jpg"/><div><b>Caldwell</b><span>Launch community</span></div></div></section><section className="section-head"><h2>Caldwell side quests</h2></section><CollectionGrid setView={p.setView}/></>}
function Collections({setView}){return <><Page eyebrow="RURAL ROUTES" title="Collections" text="Turtle Trail is now the complete feature demo inside the larger Rural Routes site. Other collections remain available as expansion shells."/><CollectionGrid setView={setView}/></>}
function CollectionGrid({setView}){return <div className="grid cards">{collections.map(c=><article className="turtle-card" key={c.id} onClick={()=>c.id==='turtle'?setView('turtleHome'):null}><div className="imgwrap"><img src={c.image}/><span className="num">{c.count}</span></div><h3>{c.title}</h3><p>{c.text}</p><small>{c.status}</small><div className="chips"><span>{c.id==='turtle'?'Open collection':'Expansion shell'}</span></div></article>)}</div>}
function Towns(){return <><Page eyebrow="ROUTE NETWORK" title="Towns" text="A multi-town framework remains in place while Caldwell becomes the first complete proof-of-concept."/><div className="grid cards">{towns.map((t,i)=><article className="feature" key={t}><Building2/><h3>{t}</h3><p>{t==='Caldwell'?'Active demo town with Turtle Trail Complete Edition.':'Expansion town ready for local routes, collections, and sponsors.'}</p><span className="hint">Town #{i+1}</span></article>)}</div></>}
function TurtleHome(p){const c=completion(p.progress);const pct=Math.round(c.visited/c.total*100);return <><section className="hero"><div className="hero-copy"><div className="eyebrow">CALDWELL TURTLE TRAIL</div><h1>Turtle Trail Complete Edition</h1><p className="lead">Find all 12 ornate box turtle sculptures, meet the artists, explore Behind the Shell stories, follow themed story paths, scan QR stops, and earn the Turtle Master badge.</p><div className="actions"><button onClick={()=>p.setView('trail')}><Footprints/>Start trail</button><button className="secondary" onClick={()=>p.setView('near')}><LocateFixed/>Near me</button><button className="ghost" onClick={()=>p.setView('map')}><MapIcon/>Map all turtles</button></div></div><div className="hero-card"><img src="/images/turtles/outlaw.jpg"/><div><b>{pct}% discovered</b><span>{c.visited}/{c.total} turtles visited</span></div></div></section><section className="section-head"><div><span className="eyebrow">TURTLE FEATURES</span><h2>Feature parity demo</h2></div></section><div className="feature-grid"><Feature icon={<BookOpen/>} title="Behind the Shell" text="Read story, symbols, theme, and design notes for each sculpture." go={()=>p.setView('trail')}/><Feature icon={<Palette/>} title="Meet the Artists" text="Artist bios, hometowns, and the turtle sculptures each artist created." go={()=>p.setView('artists')}/><Feature icon={<Route/>} title="Story Paths" text="Follow Community, Heritage, Prairie, Creativity, and Behind the Shell routes." go={()=>p.setView('paths')}/><Feature icon={<MapPin/>} title="Near Me + Map" text="Sort by distance, open directions, and view all 12 turtle stops on a map." go={()=>p.setView('near')}/></div><section className="section-head"><div><span className="eyebrow">QUICK START</span><h2>Featured turtles</h2></div><button className="ghost" onClick={()=>p.setView('trail')}>View all <ChevronRight/></button></section><TurtleGrid turtles={turtles.slice(0,4)} {...p}/></>}
function Feature({icon,title,text,go}){return <article className="feature" onClick={go}>{icon}<h3>{title}</h3><p>{text}</p><button className="ghost">Open <ChevronRight size={16}/></button></article>}
function Stats({progress}){const c=completion(progress);return <div className="stats"><Stat n={progress.points} t="Explorer points"/><Stat n={`${c.visited}/12`} t="Turtles visited"/><Stat n={`${c.scanned}/12`} t="QR scans"/><Stat n={`${progress.completedPaths.length}/5`} t="Story paths"/></div>}
function Stat({n,t}){return <div className="stat"><strong>{n}</strong><span>{t}</span></div>}
function Trail(p){const list=turtles.filter(t=>(t.name+t.artist+t.theme+t.subtitle).toLowerCase().includes(p.query.toLowerCase()));return <><Page eyebrow="COMPLETE COLLECTION" title="Caldwell Turtle Trail" text="Every turtle has a photo, sketch, artist, Behind the Shell story, GPS point, QR payload, passport progress, and map link."/><div className="toolbar"><div className="search"><Search/><input value={p.query} onChange={e=>p.setQuery(e.target.value)} placeholder="Search turtle, artist, theme"/></div><button onClick={()=>p.setView('scan')}><ScanLine/>Scan</button></div><TurtleGrid turtles={list} {...p}/></>}
function TurtleGrid({turtles,setSelected,setView,progress}){return <div className="grid cards">{turtles.map(t=>{const ok=progress.visited.includes(t.slug);return <article className="turtle-card" key={t.slug} onClick={()=>{setSelected(t);setView('turtle')}}><div className="imgwrap"><img src={t.image}/><span className="num">#{t.number}</span><span className="status">{ok?<CheckCircle2/>:<Lock/>}</span></div><h3>{t.name}</h3><p>{t.subtitle}</p><small>{t.artist}</small><div className="chips"><span>{t.theme}</span><span>{t.gpsRadiusMeters}m radius</span></div></article>})}</div>}
function TurtleDetail(p){const t=p.selected;const artist=artists.find(a=>a.name===t.artist);const visited=p.progress.visited.includes(t.slug),scanned=p.progress.scanned.includes(t.slug),photo=p.progress.photos.includes(t.slug),shell=p.progress.viewedShell.includes(t.slug);return <><button className="back" onClick={()=>p.setView('trail')}>← Turtle Trail</button><section className="detail"><div className="detail-media"><img className="main-img" src={t.image}/><img className="sketch" src={t.sketch}/></div><div className="detail-copy"><span className="eyebrow">TURTLE #{t.number}</span><h1>{t.name}</h1><p className="lead">{t.subtitle}</p><div className="chips"><span>{t.theme}</span><span>{t.storyPath}</span><span>{t.discoveryPoints}+{t.scanPoints} pts</span></div><div className="actions wrap"><button onClick={()=>p.update('visit',t)}>{visited?<CheckCircle2/>:<MapPin/>}{visited?'Visited':'Mark visited'}</button><button className="secondary" onClick={()=>p.update('scan',t)}>{scanned?<CheckCircle2/>:<QrCode/>}{scanned?'Scanned':'Demo scan'}</button><button className="secondary" onClick={()=>p.update('photo',t)}>{photo?<CheckCircle2/>:<Camera/>}{photo?'Photo logged':'Photo taken'}</button><a className="btn ghost" target="_blank" href={`https://www.google.com/maps/search/?api=1&query=${t.latitude},${t.longitude}`}><Navigation/>Directions</a></div></div></section><div className="two-col"><article className="panel"><div className="panel-head"><BookOpen/><h2>Behind the Shell</h2></div><p>{t.behindTheShell}</p><button onClick={()=>p.update('shell',t)}>{shell?'Story viewed':'Mark story viewed'}</button></article><article className="panel"><div className="panel-head"><Palette/><h2>Meet the Artist</h2></div><h3>{t.artist}</h3><p><b>{artist?.home||t.artistHome}</b></p><p>{artist?.bio||t.artistBio}</p><button className="secondary" onClick={()=>{p.markArtist(t.artist);p.setView('artists')}}>Open artists</button></article></div><article className="panel"><div className="panel-head"><Info/><h2>QR + GPS</h2></div><p><b>QR payload:</b> {t.qrPayload}</p><p><b>Location:</b> {t.latitude}, {t.longitude}</p><p><b>Discovery radius:</b> {t.gpsRadiusMeters} meters</p></article></>}
function TurtleMap(p){const minLat=Math.min(...turtles.map(t=>t.latitude)),maxLat=Math.max(...turtles.map(t=>t.latitude)),minLng=Math.min(...turtles.map(t=>t.longitude)),maxLng=Math.max(...turtles.map(t=>t.longitude));const xy=t=>({x:8+(t.longitude-minLng)/(maxLng-minLng)*84,y:88-(t.latitude-minLat)/(maxLat-minLat)*76});return <><Page eyebrow="ALL 12 STOPS" title="Turtle Trail Map" text="Use the map for an overview, then open turn-by-turn directions to any turtle."/><div className="map-layout"><div className="map"><div className="street h one">Caldwell Turtle Trail</div><div className="street v two">Main Street</div>{turtles.map(t=>{const pnt=xy(t);return <button key={t.slug} className="pin" style={{left:pnt.x+'%',top:pnt.y+'%'}} onClick={()=>{p.setSelected(t);p.setView('turtle')}}><span>{t.number}</span></button>})}</div><aside className="panel list">{turtles.map(t=><button key={t.slug} className="row" onClick={()=>{p.setSelected(t);p.setView('turtle')}}><b>#{t.number} {t.name}</b><span>{t.artist}</span></button>)}</aside></div></>}
function NearMe(p){const fallback={lat:37.032,lng:-97.61};const user=p.pos||fallback;const sorted=[...turtles].map(t=>({...t,dist:haversine(user,{lat:t.latitude,lng:t.longitude})})).sort((a,b)=>a.dist-b.dist);function locate(){navigator.geolocation?.getCurrentPosition(r=>p.setPos({lat:r.coords.latitude,lng:r.coords.longitude}),()=>alert('Location unavailable; showing demo distances.'))}return <><Page eyebrow="LOCATION-AWARE" title="Near Me" text="Sorts all turtles by distance. Uses live GPS if permitted, otherwise a Caldwell demo location."/><div className="actions"><button onClick={locate}><LocateFixed/>Use my location</button><button className="ghost" onClick={()=>p.setView('map')}><MapIcon/>Map all</button></div><div className="near-list">{sorted.map(t=><article className="near" key={t.slug}><img src={t.image}/><div><h3>#{t.number} {t.name}</h3><p>{t.artist}</p><span>{t.dist.toFixed(2)} miles away</span></div><button onClick={()=>{p.setSelected(t);p.setView('turtle')}}>Open</button></article>)}</div></>}
function Artists(p){return <><Page eyebrow="MEET THE ARTISTS" title="Artist Gallery" text="Artist profiles are part of the Turtle Trail experience, not a separate afterthought."/><div className="grid artist-grid">{artists.map(a=><article className="artist" key={a.name}><div className="artist-img"><Palette/></div><h3>{a.name}</h3><p><b>{a.home}</b></p><p>{a.bio}</p><div className="chips">{a.turtles.map(t=><button key={t} onClick={()=>{const turtle=turtles.find(x=>x.name===t); if(turtle){p.setSelected(turtle);p.setView('turtle')}}}>{t}</button>)}</div></article>)}</div></>}
function StoryPaths(p){return <><Page eyebrow="STORY PATHS" title="Choose how you explore" text="The same turtles become different experiences depending on the path you follow."/><div className="grid path-grid">{storyPaths.map(path=>{const count=path.turtles.filter(n=>p.progress.visited.includes(turtles.find(t=>t.name===n)?.slug)).length;return <article className="path" key={path.name}><Route/><h3>{path.name}</h3><p>Visit {path.turtles.length} turtles to earn the {path.rewardBadge}.</p><div className="bar"><i style={{width:(count/path.turtles.length*100)+'%'}}/></div><small>{count}/{path.turtles.length} complete</small><div className="path-turtles">{path.turtles.map(n=><button key={n} onClick={()=>{const t=turtles.find(x=>x.name===n);p.setSelected(t);p.setView('turtle')}}>{n}</button>)}</div><button onClick={()=>p.completePath(path)}>Mark path complete</button></article>})}</div></>}
function Passport(p){return <><Page eyebrow="DIGITAL PASSPORT" title="Turtle Passport" text="Track visits, QR scans, photos, Behind the Shell stories, story paths, and Turtle Master achievements."/><Stats progress={p.progress}/><div className="passport-grid">{turtles.map(t=><article className="stamp" key={t.slug}><img src={t.image}/><h3>#{t.number} {t.name}</h3><Checklist label="Visited" ok={p.progress.visited.includes(t.slug)}/><Checklist label="QR scanned" ok={p.progress.scanned.includes(t.slug)}/><Checklist label="Photo logged" ok={p.progress.photos.includes(t.slug)}/><Checklist label="Behind the Shell" ok={p.progress.viewedShell.includes(t.slug)}/></article>)}</div><section className="section-head"><h2>Achievements</h2><button className="ghost" onClick={()=>{localStorage.removeItem(key);p.setProgress(seed)}}><RefreshCcw/>Reset demo</button></section><div className="grid achievements">{achievements.map(a=><article className="achievement" key={a.id}><Trophy/><h3>{a.name}</h3><p>{a.requirement}</p><b>{a.reward}</b></article>)}</div></>}
function Profile(p){return <><Page eyebrow="EXPLORER PROFILE" title="Your Rural Routes progress" text="Profile connects the larger site to Turtle Trail progress and future town collections."/><Stats progress={p.progress}/><div className="two-col"><article className="panel"><h2>Current focus</h2><p>Caldwell Turtle Trail Complete Edition</p><button onClick={()=>p.setView('turtleHome')}>Continue trail</button></article><article className="panel"><h2>Future expansion</h2><p>Murals, Fallen Badges, Women of the Border Queen, Borderlands Legends, and town routes will plug into this same progress system.</p></article></div></>}
function Checklist({label,ok}){return <p className={ok?'ok':''}>{ok?<CheckCircle2/>:<Lock/>}{label}</p>}
function Scan(p){const[raw,setRaw]=useState('borderlands://turtle/1');function simulate(){let t=turtles.find(x=>x.qrPayload===raw||raw.includes('/'+x.number)||raw.includes(x.slug));if(t){p.setSelected(t);p.update('scan',t);p.setView('turtle')}else alert('QR not recognized in demo')}return <><Page eyebrow="UNIVERSAL QR" title="Turtle Trail Scanner" text="Demo scanner recognizes Turtle Trail QR payloads and applies scan points. Camera scanning can be added later with BarcodeDetector support."/><div className="scan-panel"><QrCode size={72}/><input value={raw} onChange={e=>setRaw(e.target.value)} /><button onClick={simulate}><ScanLine/>Demo unlock</button><div className="demo-list">{turtles.map(t=><button className="ghost" key={t.slug} onClick={()=>setRaw(t.qrPayload)}>#{t.number} {t.name}</button>)}</div><img className="wide-img" src="/images/qr/turtle-qr-codes.png"/></div></>}
function Page({eyebrow,title,text}){return <section className="page"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p className="lead">{text}</p></section>}
function Nav({view,setView}){const tabs=[['home',HomeIcon,'Explore'],['towns',Building2,'Towns'],['collections',Images,'Collections'],['turtleHome',Footprints,'Turtles'],['near',LocateFixed,'Near'],['map',MapIcon,'Map'],['scan',QrCode,'Scan'],['profile',User,'Profile']];return <nav>{tabs.map(([id,Icon,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon size={19}/><span>{label}</span></button>)}</nav>}
createRoot(document.getElementById('root')).render(<App/>);
