import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{MapPin,Navigation,Compass,QrCode,Trophy,User,Palette,BookOpen,Map as MapIcon,Footprints,CheckCircle2,Lock,Camera,Route,Search,RefreshCcw,ScanLine,ChevronRight,Star,Info,LocateFixed}from'lucide-react';
import turtleData from './turtleTrail.json';
import artistData from './artists.json';
import pathData from './storyPaths.json';
import achievementData from './achievements.json';
import './styles.css';

const key='rr-turtle-complete-v1';
const seed={points:125,visited:['outlaw','bartholomew'],scanned:['outlaw'],photos:['outlaw'],viewedShell:['outlaw','bartholomew'],viewedArtists:['Nelson P. Nelson'],completedPaths:[]};
const load=()=>{try{return JSON.parse(localStorage.getItem(key))||seed}catch{return seed}};
const save=v=>localStorage.setItem(key,JSON.stringify(v));
const turtles=turtleData.turtles;
const artists=artistData.artists;
const storyPaths=pathData.storyPaths;
const achievements=achievementData.achievements;
const slug=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
function haversine(a,b){const R=3958.8;const dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180;const lat1=a.lat*Math.PI/180,lat2=b.lat*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function App(){
 const[view,setView]=useState('home'),[selected,setSelected]=useState(turtles[0]),[progress,setProgress]=useState(load),[pos,setPos]=useState(null),[query,setQuery]=useState('');
 useEffect(()=>save(progress),[progress]);
 useEffect(()=>{navigator.serviceWorker?.register('/sw.js').catch(()=>{})},[]);
 function update(type,turtle){setProgress(p=>{const field=type==='visit'?'visited':type==='scan'?'scanned':type==='photo'?'photos':'viewedShell';if(p[field].includes(turtle.slug))return p;const add=type==='visit'?turtle.discoveryPoints:type==='scan'?turtle.scanPoints:type==='photo'?25:10;return{...p,points:p.points+add,[field]:[...p[field],turtle.slug]}})}
 function markArtist(name){setProgress(p=>p.viewedArtists.includes(name)?p:{...p,points:p.points+15,viewedArtists:[...p.viewedArtists,name]})}
 function completePath(path){setProgress(p=>p.completedPaths.includes(path.name)?p:{...p,points:p.points+100,completedPaths:[...p.completedPaths,path.name]})}
 const api={view,setView,selected,setSelected,progress,setProgress,update,markArtist,completePath,pos,setPos,query,setQuery};
 return <><main className="app">{view==='home'&&<Home {...api}/>} {view==='trail'&&<Trail {...api}/>} {view==='turtle'&&<TurtleDetail {...api}/>} {view==='map'&&<TurtleMap {...api}/>} {view==='near'&&<NearMe {...api}/>} {view==='artists'&&<Artists {...api}/>} {view==='paths'&&<StoryPaths {...api}/>} {view==='passport'&&<Passport {...api}/>} {view==='scan'&&<Scan {...api}/>} </main><Nav view={view} setView={setView}/></>}
function completion(progress){return{visited:progress.visited.length,scanned:progress.scanned.length,photos:progress.photos.length,shell:progress.viewedShell.length,total:turtles.length}}
function Home(p){const c=completion(p.progress);const pct=Math.round(c.visited/c.total*100);return <><section className="hero"><div className="hero-copy"><div className="eyebrow">CALDWELL TURTLE TRAIL</div><h1>Turtle Trail Complete Edition</h1><p className="lead">Find all 12 ornate box turtle sculptures, meet the artists, explore Behind the Shell stories, follow themed story paths, scan QR stops, and earn the Turtle Master badge.</p><div className="actions"><button onClick={()=>p.setView('trail')}><Footprints/>Start trail</button><button className="secondary" onClick={()=>p.setView('near')}><LocateFixed/>Near me</button><button className="ghost" onClick={()=>p.setView('map')}><MapIcon/>Map all turtles</button></div></div><div className="hero-card"><img src="/images/turtles/outlaw.jpg"/><div><b>{pct}% discovered</b><span>{c.visited}/{c.total} turtles visited</span></div></div></section><Stats progress={p.progress}/><section className="section-head"><div><span className="eyebrow">TURTLE FEATURES</span><h2>Four ways to explore</h2></div></section><div className="feature-grid"><Feature icon={<BookOpen/>} title="Behind the Shell" text="Read the story, symbols, theme, and design notes for each sculpture." go={()=>p.setView('trail')}/><Feature icon={<Palette/>} title="Meet the Artists" text="Artist bios, hometowns, and the turtle sculptures each artist created." go={()=>p.setView('artists')}/><Feature icon={<Route/>} title="Story Paths" text="Follow Community, Heritage, Kansas & Prairie, Creativity, and Behind the Shell routes." go={()=>p.setView('paths')}/><Feature icon={<MapPin/>} title="Near Me + Map" text="Sort by distance, open directions, and view all 12 turtle stops on a map." go={()=>p.setView('near')}/></div><section className="section-head"><div><span className="eyebrow">QUICK START</span><h2>Featured turtles</h2></div><button className="ghost" onClick={()=>p.setView('trail')}>View all <ChevronRight/></button></section><TurtleGrid turtles={turtles.slice(0,4)} {...p}/></>}
function Feature({icon,title,text,go}){return <article className="feature" onClick={go}>{icon}<h3>{title}</h3><p>{text}</p><button className="ghost">Open <ChevronRight size={16}/></button></article>}
function Stats({progress}){const c=completion(progress);return <div className="stats"><Stat n={progress.points} t="Explorer points"/><Stat n={`${c.visited}/12`} t="Visited"/><Stat n={`${c.scanned}/12`} t="QR scans"/><Stat n={`${progress.completedPaths.length}/5`} t="Story paths"/></div>}
function Stat({n,t}){return <div className="stat"><strong>{n}</strong><span>{t}</span></div>}
function Trail(p){const list=turtles.filter(t=>(t.name+t.artist+t.theme+t.subtitle).toLowerCase().includes(p.query.toLowerCase()));return <><Page eyebrow="COMPLETE COLLECTION" title="Caldwell Turtle Trail" text="Every turtle has a photo, sketch, artist, Behind the Shell story, GPS point, QR payload, passport progress, and map link."/><div className="toolbar"><div className="search"><Search/><input value={p.query} onChange={e=>p.setQuery(e.target.value)} placeholder="Search turtle, artist, theme"/></div><button onClick={()=>p.setView('scan')}><ScanLine/>Scan</button></div><TurtleGrid turtles={list} {...p}/></>}
function TurtleGrid({turtles,setSelected,setView,progress}){return <div className="grid cards">{turtles.map(t=>{const ok=progress.visited.includes(t.slug);return <article className="turtle-card" key={t.slug} onClick={()=>{setSelected(t);setView('turtle')}}><div className="imgwrap"><img src={t.image}/><span className="num">#{t.number}</span><span className="status">{ok?<CheckCircle2/>:<Lock/>}</span></div><h3>{t.name}</h3><p>{t.subtitle}</p><small>{t.artist}</small><div className="chips"><span>{t.theme}</span><span>{t.gpsRadiusMeters}m radius</span></div></article>})}</div>}
function TurtleDetail(p){const t=p.selected;const artist=artists.find(a=>a.name===t.artist);const visited=p.progress.visited.includes(t.slug),scanned=p.progress.scanned.includes(t.slug),photo=p.progress.photos.includes(t.slug),shell=p.progress.viewedShell.includes(t.slug);return <><button className="back" onClick={()=>p.setView('trail')}>← Turtle Trail</button><section className="detail"><div className="detail-media"><img className="main-img" src={t.image}/><img className="sketch" src={t.sketch}/></div><div className="detail-copy"><span className="eyebrow">TURTLE #{t.number}</span><h1>{t.name}</h1><p className="lead">{t.subtitle}</p><div className="chips"><span>{t.theme}</span><span>{t.storyPath}</span><span>{t.discoveryPoints}+{t.scanPoints} pts</span></div><div className="actions wrap"><button onClick={()=>p.update('visit',t)}>{visited?<CheckCircle2/>:<MapPin/>}{visited?'Visited':'Mark visited'}</button><button className="secondary" onClick={()=>p.update('scan',t)}>{scanned?<CheckCircle2/>:<QrCode/>}{scanned?'Scanned':'Demo scan'}</button><button className="secondary" onClick={()=>p.update('photo',t)}>{photo?<CheckCircle2/>:<Camera/>}{photo?'Photo logged':'Photo taken'}</button><a className="btn ghost" target="_blank" href={`https://www.google.com/maps/search/?api=1&query=${t.latitude},${t.longitude}`}><Navigation/>Directions</a></div></div></section><div className="two-col"><article className="panel"><div className="panel-head"><BookOpen/><h2>Behind the Shell</h2></div><p>{t.behindTheShell}</p><button onClick={()=>p.update('shell',t)}>{shell?'Story viewed':'Mark story viewed'}</button></article><article className="panel"><div className="panel-head"><Palette/><h2>Meet the Artist</h2></div><h3>{t.artist}</h3><p><b>{artist?.home||t.artistHome}</b></p><p>{artist?.bio||t.artistBio}</p><button className="secondary" onClick={()=>{p.markArtist(t.artist);p.setView('artists')}}>Open artists</button></article></div><article className="panel"><div className="panel-head"><Info/><h2>QR + GPS</h2></div><p><b>QR payload:</b> {t.qrPayload}</p><p><b>Location:</b> {t.latitude}, {t.longitude}</p><p><b>Discovery radius:</b> {t.gpsRadiusMeters} meters</p></article></>}
function TurtleMap(p){const minLat=Math.min(...turtles.map(t=>t.latitude)),maxLat=Math.max(...turtles.map(t=>t.latitude)),minLng=Math.min(...turtles.map(t=>t.longitude)),maxLng=Math.max(...turtles.map(t=>t.longitude));const xy=t=>({x:8+(t.longitude-minLng)/(maxLng-minLng)*84,y:88-(t.latitude-minLat)/(maxLat-minLat)*76});return <><Page eyebrow="ALL 12 STOPS" title="Turtle Trail Map" text="Use the map for an overview, then open turn-by-turn directions to any turtle."/><div className="map-layout"><div className="map"><div className="street h one">Caldwell</div><div className="street v two">Main Street</div>{turtles.map(t=>{const pnt=xy(t);return <button key={t.slug} className="pin" style={{left:pnt.x+'%',top:pnt.y+'%'}} onClick={()=>{p.setSelected(t);p.setView('turtle')}}><span>{t.number}</span></button>})}</div><aside className="panel list">{turtles.map(t=><button key={t.slug} className="row" onClick={()=>{p.setSelected(t);p.setView('turtle')}}><b>#{t.number} {t.name}</b><span>{t.artist}</span></button>)}</aside></div></>}
function NearMe(p){const[busy,setBusy]=useState(false);function locate(){setBusy(true);navigator.geolocation?.getCurrentPosition(x=>{p.setPos({lat:x.coords.latitude,lng:x.coords.longitude});setBusy(false)},()=>{p.setPos({lat:37.0313,lng:-97.6113,demo:true});setBusy(false)},{enableHighAccuracy:true,timeout:8000})}const base=p.pos||{lat:37.0313,lng:-97.6113,demo:true};const sorted=turtles.map(t=>({...t,distance:haversine(base,{lat:t.latitude,lng:t.longitude})})).sort((a,b)=>a.distance-b.distance);return <><Page eyebrow="LOCATION-AWARE TRAIL" title="Near Me" text="Sorts turtle stops by distance. If location permission is unavailable, the demo uses central Caldwell as the starting point."/><div className="toolbar"><button onClick={locate}><LocateFixed/>{busy?'Locating…':'Use my location'}</button><span className="hint">{p.pos?(p.pos.demo?'Demo location: downtown Caldwell':'Using your current location'):'No location yet'}</span></div><div className="near-list">{sorted.map(t=><article className="near" key={t.slug}><img src={t.image}/><div><b>#{t.number} {t.name}</b><p>{t.subtitle} • {t.artist}</p><span>{t.distance<0.1?`${Math.round(t.distance*5280)} ft`:`${t.distance.toFixed(2)} mi`} away</span></div><button className="secondary" onClick={()=>{p.setSelected(t);p.setView('turtle')}}>Open</button></article>)}</div></>}
function Artists(p){return <><Page eyebrow="MEET THE ARTISTS" title="Artists of the Turtle Trail" text="Artist profiles connect visitors to the people behind Caldwell’s public art."/><div className="grid artist-grid">{artists.map(a=><article className="artist" key={a.name}><div className="artist-img"><Palette size={38}/></div><h3>{a.name}</h3><p><b>{a.home}</b></p><p>{a.bio}</p><div className="chips">{a.turtles.map(n=><button key={n} onClick={()=>{p.setSelected(turtles.find(t=>t.name===n));p.markArtist(a.name);p.setView('turtle')}}>{n}</button>)}</div></article>)}</div><article className="panel"><h2>Artist brochure asset</h2><img className="wide-img" src="/images/artists/artist-bios-brochure.jpg"/></article></>}
function StoryPaths(p){return <><Page eyebrow="CHOOSE YOUR ADVENTURE" title="Story Paths" text="Story paths let families, art lovers, and history fans experience the same sculpture trail through different themes."/><div className="grid path-grid">{storyPaths.map(path=>{const done=path.turtles.filter(n=>p.progress.visited.includes(slug(n))).length;return <article className="path" key={path.name}><Route/><h3>{path.name}</h3><p>Reward: <b>{path.rewardBadge}</b></p><div className="bar"><i style={{width:(done/path.turtles.length*100)+'%'}}/></div><small>{done}/{path.turtles.length} turtles visited</small><div className="path-turtles">{path.turtles.map(n=><button key={n} onClick={()=>{p.setSelected(turtles.find(t=>t.name===n));p.setView('turtle')}}>{n}</button>)}</div><button onClick={()=>p.completePath(path)}>{p.progress.completedPaths.includes(path.name)?'Completed':'Complete demo path'}</button></article>})}</div></>}
function Passport(p){const c=completion(p.progress);return <><Page eyebrow="PASSPORT + ACHIEVEMENTS" title="Turtle Master Progress" text="Track discovery, QR scans, photos, Behind the Shell reads, and story path completion."/><Stats progress={p.progress}/><div className="passport-grid">{turtles.map(t=><article className="stamp" key={t.slug}><img src={t.image}/><h3>{t.name}</h3><Checklist label="Visited" ok={p.progress.visited.includes(t.slug)}/><Checklist label="QR scanned" ok={p.progress.scanned.includes(t.slug)}/><Checklist label="Photo" ok={p.progress.photos.includes(t.slug)}/><Checklist label="Behind the Shell" ok={p.progress.viewedShell.includes(t.slug)}/></article>)}</div><section className="section-head"><h2>Achievements</h2><button className="ghost" onClick={()=>{localStorage.removeItem(key);p.setProgress(seed)}}><RefreshCcw/>Reset demo</button></section><div className="grid achievements">{achievements.map(a=><article className="achievement" key={a.id}><Trophy/><h3>{a.name}</h3><p>{a.requirement}</p><b>{a.reward}</b></article>)}</div></>}
function Checklist({label,ok}){return <p className={ok?'ok':''}>{ok?<CheckCircle2/>:<Lock/>}{label}</p>}
function Scan(p){const[raw,setRaw]=useState('borderlands://turtle/1');function simulate(){let t=turtles.find(x=>x.qrPayload===raw||raw.includes('/'+x.number)||raw.includes(x.slug));if(t){p.setSelected(t);p.update('scan',t);p.setView('turtle')}else alert('QR not recognized in demo')}return <><Page eyebrow="UNIVERSAL QR" title="Turtle Trail Scanner" text="Demo scanner recognizes Turtle Trail QR payloads and applies scan points. Camera scanning can be added later with BarcodeDetector support."/><div className="scan-panel"><QrCode size={72}/><input value={raw} onChange={e=>setRaw(e.target.value)} /><button onClick={simulate}><ScanLine/>Demo unlock</button><div className="demo-list">{turtles.map(t=><button className="ghost" key={t.slug} onClick={()=>setRaw(t.qrPayload)}>#{t.number} {t.name}</button>)}</div><img className="wide-img" src="/images/qr/turtle-qr-codes.png"/></div></>}
function Page({eyebrow,title,text}){return <section className="page"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p className="lead">{text}</p></section>}
function Nav({view,setView}){const tabs=[['home',Compass,'Home'],['trail',Footprints,'Trail'],['near',LocateFixed,'Near'],['map',MapIcon,'Map'],['paths',Route,'Paths'],['artists',Palette,'Artists'],['passport',Trophy,'Passport']];return <nav>{tabs.map(([id,Icon,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon size={19}/><span>{label}</span></button>)}</nav>}
createRoot(document.getElementById('root')).render(<App/>);
