import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{MapPin,QrCode,Trophy,User,Compass,Camera,Stamp,Map as MapIcon,CheckCircle2,Lock,Download,ChevronRight,Settings,Route,Shield,Star,Search,RotateCcw,Save,Gift,Navigation}from'lucide-react';
import'./styles.css';
import{towns,collections,achievements,caldwellStops,adminDefaults}from'./data';

const progressKey='rr-phase2-progress-v1';
const adminKey='rr-phase2-admin-v1';
const seed={points:650,stamps:['caldwell','turtles'],unlocked:['turtle-1','turtle-2','badge-1','queen-1','legend-1','mural-1'],scans:[{id:'turtle-1',source:'seed',when:Date.now()-86400000},{id:'badge-1',source:'seed',when:Date.now()-3600000}]};
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const save=(key,val)=>localStorage.setItem(key,JSON.stringify(val));
function App(){
 const[view,setView]=useState('explore');
 const[progress,setProgress]=useState(()=>load(progressKey,seed));
 const[admin,setAdmin]=useState(()=>load(adminKey,adminDefaults));
 const[collection,setCollection]=useState(collections[0]);
 const[modal,setModal]=useState(null);
 const[scanMsg,setScanMsg]=useState('Ready. Scan a Rural Routes QR or use a demo unlock.');
 const[install,setInstall]=useState(null);
 const[query,setQuery]=useState('');
 useEffect(()=>save(progressKey,progress),[progress]);
 useEffect(()=>save(adminKey,admin),[admin]);
 useEffect(()=>{const h=e=>{e.preventDefault();setInstall(e)};window.addEventListener('beforeinstallprompt',h);navigator.serviceWorker?.register('/sw.js').catch(()=>{});return()=>window.removeEventListener('beforeinstallprompt',h)},[]);
 const allItems=useMemo(()=>collections.flatMap(c=>c.items.map(i=>({...i,collection:c.title,collectionId:c.id}))),[]);
 const unlocked=new Set(progress.unlocked);
 function unlock(item,source='manual'){if(!item)return;setProgress(p=>p.unlocked.includes(item.id)?p:{...p,points:p.points+(item.points||admin.pointsPerScan),unlocked:[...p.unlocked,item.id],scans:[...p.scans,{id:item.id,source,when:Date.now()}]});setScanMsg(`Unlocked ${item.name}. +${item.points||admin.pointsPerScan} explorer points.`)}
 function onQr(raw){const item=allItems.find(i=>i.qr===raw||raw?.includes(i.qr)); if(item){unlock(item,'qr');setCollection(collections.find(c=>c.id===item.collectionId)||collections[0]);setView('rewards')} else setScanMsg(`QR not recognized: ${raw}`)}
 function resetDemo(){localStorage.removeItem(progressKey);setProgress(seed)}
 return <><div className="app-shell"><main className="app">
  {view==='explore'&&<Explore admin={admin} progress={progress} setView={setView} setCollection={setCollection} query={query} setQuery={setQuery}/>} 
  {view==='towns'&&<Towns setView={setView}/>} 
  {view==='caldwell'&&<Caldwell setView={setView} setCollection={setCollection}/>} 
  {view==='map'&&<MapView/>}
  {view==='scan'&&<ScanView onQr={onQr} scanMsg={scanMsg} allItems={allItems}/>} 
  {view==='rewards'&&<Rewards collection={collection} setCollection={setCollection} unlocked={unlocked} setModal={setModal} unlock={unlock} progress={progress}/>} 
  {view==='profile'&&<Profile progress={progress} resetDemo={resetDemo}/>} 
  {view==='admin'&&<Admin admin={admin} setAdmin={setAdmin}/>} 
 </main></div><BottomNav view={view} setView={setView}/><CardModal modal={modal} setModal={setModal}/>{install&&<button className="install" onClick={()=>install.prompt()}><Download size={18}/>Install</button>}</>}
function Explore({admin,progress,setView,setCollection,query,setQuery}){const featured=collections.slice(0,4);return <>
 <section className="hero glass"><div className="hero-art"><img src="/assets/logo.jpg"/><div className="badge-ribbon">Phase 2 Demo</div></div><div><div className="eyebrow">RURAL ROUTES EXPLORER</div><h1>{admin.headline}</h1><p className="lead">A mobile-first tourism experience for small towns: side quests, QR unlocks, local history cards, passport stamps, public art, maps, and reward moments.</p><div className="hero-actions"><button onClick={()=>setView('caldwell')}><Compass size={18}/>Explore Caldwell</button><button className="secondary" onClick={()=>setView('scan')}><QrCode size={18}/>Scan / unlock</button><button className="ghost" onClick={()=>setView('map')}><MapPin size={18}/>Open map</button></div><div className="announcement"><Gift size={18}/><span>{admin.announcement}</span></div></div></section>
 <Stats progress={progress}/>
 <section className="section-head"><div><span className="eyebrow">CALDWELL DEMO</span><h2>Featured side quests</h2></div><button className="ghost" onClick={()=>setView('caldwell')}>Town detail <ChevronRight size={16}/></button></section>
 <div className="grid quests">{featured.map(c=><Quest key={c.id} c={c} progress={progress} onStart={()=>{setCollection(c);setView(c.id==='murals'?'map':'rewards')}}/>)}</div>
 <section className="section-head"><div><span className="eyebrow">REGIONAL PRODUCT</span><h2>Town directory</h2></div><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search towns"/></div></section>
 <TownGrid towns={towns.filter(t=>(t.name+t.tagline+t.hero).toLowerCase().includes(query.toLowerCase()))} setView={setView}/>
 </>}
function Stats({progress}){const next=Math.ceil((progress.points+1)/500)*500;const pct=Math.min(100,progress.points/next*100);return <section className="grid stats"><div className="stat featured"><div className="eyebrow">NEARBY DISCOVERY</div><h2>Explorer Level {Math.max(1,Math.floor(progress.points/500)+1)}</h2><p>{progress.points} points earned. Next level at {next}.</p><div className="progress"><div style={{width:`${pct}%`}}/></div></div><div className="stat"><Stamp/><strong>{progress.stamps.length}</strong><span>Passport stamps</span></div><div className="stat"><Star/><strong>{progress.unlocked.length}</strong><span>Cards unlocked</span></div><div className="stat"><QrCode/><strong>{progress.scans.length}</strong><span>Scans</span></div></section>}
function Quest({c,progress,onStart}){const total=c.items.length;const done=c.items.filter(i=>progress.unlocked.includes(i.id)).length;return <article className={`quest color-${c.color}`}><div className="quest-top"><span className="pill">{c.icon} {c.type}</span><b>{c.town}</b></div><h3>{c.title}</h3><p>{c.description}</p><div className="meter"><span>{done}/{total} unlocked</span><div><i style={{width:`${Math.round(done/total*100)}%`}}/></div></div><p className="small">Reward: {c.reward}</p><button onClick={onStart}>Start quest <ChevronRight size={16}/></button></article>}
function TownGrid({towns,setView}){return <div className="grid towns">{towns.map(t=><article className={`town accent-${t.accent}`} key={t.id}><span className="pill">{t.label}</span><h3>{t.name}</h3><p>{t.tagline}</p><b>{t.hero}</b><div className="card-actions"><button className="secondary" onClick={()=>t.id==='caldwell'?setView('caldwell'):window.open(`https://www.google.com/maps/search/?api=1&query=${t.lat},${t.lng}`,'_blank')}><Navigation size={16}/>{t.id==='caldwell'?'Open town':'Directions'}</button></div></article>)}</div>}
function Towns({setView}){return <><section className="page-title"><span className="eyebrow">RURAL ROUTES REGION</span><h1>Town directory</h1><p className="lead">Caldwell is built as the polished demonstration town. The remaining towns are structured as expansion slots for Phase 3 content.</p></section><TownGrid towns={towns} setView={setView}/></>}
function Caldwell({setView,setCollection}){return <><section className="town-hero glass"><div><span className="eyebrow">FEATURED DEMO TOWN</span><h1>Caldwell, Kansas</h1><p className="lead">The Border Queen demo combines walkable public art, collectible story cards, QR discovery, tourism handouts, passport stamps, and sponsor-friendly reward moments.</p><div className="hero-actions"><button onClick={()=>{setCollection(collections[0]);setView('rewards')}}>Open Turtle Trail</button><button className="secondary" onClick={()=>setView('map')}>View walking map</button></div></div><div className="town-score"><strong>5</strong><span>demo-ready quests</span><strong>52</strong><span>unlockable items</span></div></section><section className="section-head"><div><span className="eyebrow">VISITOR FLOW</span><h2>What a traveler does</h2></div></section><div className="flow"><Flow n="1" title="Arrive" text="Open the PWA from a QR code, sign, brochure, or social link."/><Flow n="2" title="Choose a quest" text="Start with Turtle Trail, Mural Quest, or history cards."/><Flow n="3" title="Unlock" text="Scan QR codes, check stops, collect cards, and earn points."/><Flow n="4" title="Claim" text="Use passport progress for badges, coupons, or sponsor rewards."/></div><section className="section-head"><div><span className="eyebrow">CALDWELL QUESTS</span><h2>Built for the demo</h2></div></section><div className="grid quests">{collections.filter(c=>c.town==='Caldwell').map(c=><Quest key={c.id} c={c} progress={{unlocked:[]}} onStart={()=>{setCollection(c);setView('rewards')}}/>)}</div></>}
function Flow({n,title,text}){return <div className="flow-card"><b>{n}</b><h3>{title}</h3><p>{text}</p></div>}
function MapView(){return <><section className="page-title"><span className="eyebrow">MAPS + ROUTES</span><h1>Caldwell walking demo</h1><p className="lead">Phase 2 uses a polished schematic map and direct map links. Phase 3 can add live pins from Supabase and turn-by-turn route layers.</p></section><div className="map-layout"><div className="mapbox polished">{caldwellStops.map(s=><button key={s.id} className="pin" style={{left:`${s.x}%`,top:`${s.y}%`}} title={s.note}>{s.title}</button>)}<div className="main-street">Main Street</div><div className="route-line one"/><div className="route-line two"/></div><aside className="panel"><h3>Map layers</h3>{caldwellStops.map(s=><div className="stop" key={s.id}><span>{s.kind}</span><b>{s.title}</b><p>{s.note}</p></div>)}<a className="btn" target="_blank" href="https://www.google.com/maps/search/Caldwell+Kansas+Main+Street">Open Caldwell in Google Maps</a></aside></div><section className="section-head"><h2>Mural handout preview</h2></section><div className="panel"><img className="handout" src="/assets/mural-handout.png"/></div></>}
function ScanView({onQr,scanMsg,allItems}){const video=useRef(null);const[active,setActive]=useState(false);async function start(){try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});video.current.srcObject=stream;await video.current.play();setActive(true);if('BarcodeDetector'in window){const detector=new BarcodeDetector({formats:['qr_code']});const timer=setInterval(async()=>{if(!video.current||video.current.paused)return;const codes=await detector.detect(video.current).catch(()=>[]);if(codes[0]){onQr(codes[0].rawValue);clearInterval(timer);stream.getTracks().forEach(t=>t.stop());setActive(false)}},700)}}catch{alert('Camera unavailable. Use demo unlocks below or test on a phone over HTTPS.')}}return <><section className="page-title"><span className="eyebrow">UNIVERSAL UNLOCK</span><h1>Scan any Rural Routes QR</h1><p className="lead">One scanner for sculpture stops, mural stops, passport stamps, story cards, and future sponsor rewards.</p></section><div className="scanbox"><div className="scanner"><video ref={video} playsInline muted style={{width:'100%',borderRadius:22,display:active?'block':'none'}}/><QrCode size={64}/><h3>{active?'Scanning…':'Ready to scan'}</h3><p>{scanMsg}</p><button onClick={start}><Camera size={18}/>Start camera</button></div><div className="panel"><h3>Desktop demo unlocks</h3><p>Use these while presenting on a laptop or before printed QR signs are placed.</p><div className="demo-list">{allItems.slice(0,12).map(i=><button key={i.id} className="ghost" onClick={()=>onQr(i.qr)}>{i.name}</button>)}</div></div></div></>}
function Rewards({collection,setCollection,unlocked,setModal,unlock,progress}){const done=collection.items.filter(i=>unlocked.has(i.id)).length;return <><section className="page-title"><span className="eyebrow">PASSPORT + COLLECTIONS</span><h1>Collectible card viewer</h1><p className="lead">Cards now feel like a tourism reward system, with locked states, front/back viewing, and quest progress.</p></section><div className="toolbar panel"><div><b>{collection.title}</b><p>{done}/{collection.items.length} unlocked • Reward: {collection.reward}</p></div><select value={collection.id} onChange={e=>setCollection(collections.find(c=>c.id===e.target.value))}>{collections.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div><div className="grid cards">{collection.items.map(i=>{const ok=unlocked.has(i.id);return <article className={`card ${ok?'unlocked':'locked'}`} key={i.id} onClick={()=>ok?setModal(i):unlock(i,'demo')}><div className="media">{i.front||i.image?<img src={i.front||i.image}/>:<div className="placeholder"><Stamp size={44}/><b>{i.name}</b></div>}<span className="number">#{i.number}</span><span className="lock">{ok?<CheckCircle2/>:<Lock/>}</span></div><h4>{i.name}</h4><p>{i.subtitle||i.type}</p><small>{ok?'Unlocked — tap to flip/view':'Locked — tap for demo unlock'}</small></article>})}</div></>}
function Profile({progress,resetDemo}){return <><section className="page-title"><span className="eyebrow">EXPLORER PROFILE</span><h1>Passport + trophy case</h1><p className="lead">A simple reward dashboard for demos. Phase 3 can add accounts, Supabase persistence, and city admin controls.</p></section><Stats progress={progress}/><div className="grid achievements">{achievements.map(a=><article className="achievement" key={a.id}><span>{a.icon}</span><h3>{a.title}</h3><p>{a.rule}</p><b>+{a.reward} points</b></article>)}</div><section className="section-head"><h2>Recent activity</h2><button className="ghost" onClick={resetDemo}><RotateCcw size={16}/>Reset demo</button></section><div className="panel">{progress.scans.length?progress.scans.slice(-10).reverse().map(s=><p key={s.when}><CheckCircle2 size={16}/> Unlocked <b>{s.id}</b> by {s.source}</p>):<p>No scans yet.</p>}</div></>}
function Admin({admin,setAdmin}){const[draft,setDraft]=useState(admin);function update(k,v){setDraft({...draft,[k]:v})}return <><section className="page-title"><span className="eyebrow">ADMIN-LITE</span><h1>Demo control panel</h1><p className="lead">Local-only editor for presentation text and scoring. This is a bridge before Supabase city-admin accounts.</p></section><div className="admin-grid"><label>Hero headline<input value={draft.headline} onChange={e=>update('headline',e.target.value)}/></label><label>Sponsor slot<input value={draft.sponsor} onChange={e=>update('sponsor',e.target.value)}/></label><label>Announcement<textarea value={draft.announcement} onChange={e=>update('announcement',e.target.value)}/></label><label>Points per scan<input type="number" value={draft.pointsPerScan} onChange={e=>update('pointsPerScan',Number(e.target.value))}/></label><label>GPS radius feet<input type="number" value={draft.gpsRadius} onChange={e=>update('gpsRadius',Number(e.target.value))}/></label></div><div className="hero-actions"><button onClick={()=>setAdmin(draft)}><Save size={18}/>Save local demo settings</button><button className="secondary" onClick={()=>{setDraft(adminDefaults);setAdmin(adminDefaults)}}>Restore defaults</button></div><div className="notice"><Shield size={18}/><span>Phase 2 admin data is saved in this browser only. Phase 3 should move this to Supabase with city roles.</span></div></>}
function CardModal({modal,setModal}){const[back,setBack]=useState(false);useEffect(()=>setBack(false),[modal]);if(!modal)return null;const hasBack=Boolean(modal.back);return <div className="modal show" onClick={()=>setModal(null)}><div className="modal-card" onClick={e=>e.stopPropagation()}><div className="toolbar"><div><span className="eyebrow">{modal.collection||modal.type}</span><h3>{modal.name}</h3></div><button className="ghost" onClick={()=>setModal(null)}>Close</button></div><div className={`flip-card ${back?'show-back':''}`}><div className="flip-inner"><div className="flip-face">{modal.front||modal.image?<img src={modal.front||modal.image}/>:<div className="placeholder tall"><Stamp size={64}/><h2>{modal.name}</h2></div>}</div>{hasBack&&<div className="flip-face back"><img src={modal.back}/></div>}</div></div><p>{modal.artist?`Artist: ${modal.artist}`:modal.hint}</p><div className="hero-actions">{hasBack&&<button onClick={()=>setBack(!back)}>Flip card</button>}{modal.sketch&&<a className="btn secondary" href={modal.sketch} target="_blank">View sketch</a>}</div></div></div>}
function BottomNav({view,setView}){const tabs=[['explore',Compass,'Explore'],['towns',Route,'Towns'],['map',MapIcon,'Map'],['scan',QrCode,'Scan'],['rewards',Trophy,'Cards'],['profile',User,'Profile'],['admin',Settings,'Admin']];return <nav className="tabbar">{tabs.map(([id,Icon,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon size={20}/><span>{label}</span></button>)}</nav>}

createRoot(document.getElementById('root')).render(<App/>);
